
services:
  portfolio.home:
    image: portfolio.home
    build:
      context: .
      dockerfile: Portfolio.Home/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080

  urlshortener:
    image: urlshortener
    build:
      context: ../UrlShortener
      dockerfile: ./UrlShortener/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080

